Update pr-prefix-check.yml

diff --git a/.github/workflows/pr-prefix-check.yml b/.github/workflows/pr-prefix-check.yml
--- a/.github/workflows/pr-prefix-check.yml
+++ b/.github/workflows/pr-prefix-check.yml
@@ -1,16 +1,17 @@
-name: Pull Request Prefix Check
+- name: Check Pull Request Prefix
+  env:
+    PR_NUMBER: ${{ github.event.number }}
+    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+    GITHUB_API_URL: ${{ github.event.repository.url }}/api/v3
+  run: |
+    set -e
 
-on:
-  pull_request:
-    types: [ opened, edited, synchronize ]
+    PREFIXES=("major:" "breaking:" "feat:" "feature:" "fix:" "hotfix:")
 
-jobs:
-  check_prefix:
-    runs-on: ubuntu-latest
-    steps:
-      - name: Check Pull Request Prefix
-        uses: ramonsnir/gh-action-pr-title@1.0.0
-        with:
-          repo-token: ${{ secrets.GITHUB_TOKEN }}
-          pattern: '^(major|breaking|feat|feature|fix|hotfix):'
-          error-message: 'Invalid pull request title. The title must start with one of the following prefixes: major:, breaking:, feat:, feature:, fix:, or hotfix:'
+    PR_TITLE=$(curl -s -H "Authorization: Bearer ${GITHUB_TOKEN}" "${GITHUB_API_URL}/repos/${GITHUB_REPOSITORY}/pulls/${PR_NUMBER}" | jq -r '.title')
+    PR_PREFIX=$(echo "${PR_TITLE}" | cut -d ':' -f 1)
+
+    if ! [[ " ${PREFIXES[@]} " =~ " ${PR_PREFIX} " ]]; then
+      echo "Error: Pull request title must start with one of the following prefixes: ${PREFIXES[*]}" >&2
+      exit 1
+    fi
